name: protein_design_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - pyg
  - bioconda
  - nodefaults
dependencies:
  - conda-forge::biotite=0.41.0
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - biotite=0.41.0
  - bioconda::nextflow
  - pip:
    - transformers
    - huggingface-hub
    - levenshtein


